# Generated by Django 5.0.1 on 2024-01-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('Stayling', 'Styling'), ('Massage', 'Massage'), ('Skin Care', 'Hautpflege')], default='Stayling', max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='service',
            field=models.CharField(choices=[('HairCut', 'Haarschnitt'), ('Beard', 'Bart'), ('Hair coloring', 'haare Färben'), ('Massage', 'Massage'), ('Maskes', 'Masken'), ('Stayling Products', 'Styling Produkte'), ('Skin Cleaning', 'Gesicht Reinigung')], default='HairCut', max_length=20, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('HairCut', 'Haarschnitt'), ('Beard', 'Bart'), ('Hair coloring', 'haare Färben'), ('Massage', 'Massage'), ('Maskes', 'Masken'), ('Stayling Products', 'Styling Produkte'), ('Skin Cleaning', 'Gesicht Reinigung')], default='HairCut', max_length=20, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Zeit'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='experience_years',
            field=models.IntegerField(verbose_name='Erfahrung Jahre'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='expertise',
            field=models.CharField(max_length=255, verbose_name='Erfahrung'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(upload_to='barber_images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(verbose_name='Beschriebeung'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Über'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(upload_to='owner_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Social Links'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Webseite'),
        ),
        migrations.AlterField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_review', to='contact.barber'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Kommentare'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='Bewertung'),
        ),
    ]
