# Generated by Django 5.0.1 on 2024-01-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_appointment_email_galleryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.barber', verbose_name='Friseur'),
        ),
        migrations.AlterField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_review', to='contact.barber', verbose_name='Friseur'),
        ),
    ]
