# Generated by Django 5.0.1 on 2024-01-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ownerprofile_owner'),
        ('contact', '0005_remove_galleryitem_user_galleryitem_name_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to='accounts.ownerprofile', verbose_name='Eigentümer'),
        ),
    ]
