# Generated by Django 5.0.1 on 2024-01-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_appointment', to='contact.appointment', verbose_name='Termine'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_reserved', to='contact.barber', verbose_name='Friseur'),
        ),
    ]
