# Generated by Django 5.0.1 on 2024-01-29 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_barber_appointment_alter_appointment_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visitor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Besucher-ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='review',
            name='visitor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Besucher-ID'),
        ),
    ]
