# Generated by Django 5.0.1 on 2024-02-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_appointment_visitor_id_review_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Bewertung'),
        ),
    ]
