# Generated by Django 5.0.1 on 2024-02-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='work_days',
            field=models.CharField(default='Montag-Freitag', max_length=255, verbose_name='Arbeits Tage'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
