# Generated by Django 5.0.1 on 2024-02-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_services',
            field=models.ManyToManyField(blank=True, to='contact.service'),
        ),
    ]
