# Generated by Django 5.0.1 on 2024-02-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_service_sub_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Category Name', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Default Service Name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_service', to='contact.service'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_service', to='contact.service'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_category', to='contact.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='contact.category'),
        ),
    ]
