# Generated by Django 5.0.1 on 2024-02-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_category_remove_service_service_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_services',
        ),
    ]
