# Generated by Django 5.0.1 on 2024-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_remove_service_sub_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visitor_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='visitor_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='visitor_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
