# Generated by Django 5.0.1 on 2024-02-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_alter_appointment_message_alter_appointment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prodcut', max_length=255, verbose_name='Element')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Foto')),
                ('description', models.TextField(verbose_name='Beschriebeung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='contact.category')),
            ],
        ),
    ]
