# Generated by Django 5.0.1 on 2024-03-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_review', to='contact.barber', verbose_name='Friseur'),
        ),
    ]
