# Generated by Django 5.0.1 on 2024-03-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_appointment_slug_barber_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_product', to='contact.product'),
        ),
    ]
