# Generated by Django 5.0.1 on 2024-03-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_product_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_service', to='contact.service'),
        ),
    ]
