# Generated by Django 5.0.1 on 2024-03-16 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_alter_appointment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Schließungszeit'),
        ),
        migrations.AddField(
            model_name='owner',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Öffnungszeit'),
        ),
    ]
