# Generated by Django 5.0.1 on 2024-04-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_owner_closing_time_owner_opening_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
