# Generated by Django 5.0.1 on 2024-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_owner_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_logos/', verbose_name='Logo'),
        ),
    ]
