# Generated by Django 5.0.1 on 2024-04-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0038_alter_category_slug_alter_galleryitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='contact.appointment', verbose_name='Termine'),
        ),
    ]
