# Generated by Django 5.0.1 on 2024-01-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='barber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Dein Name', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_user_profile', to='accounts.customuser', verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Männlich'), ('female', 'Weiblich')], max_length=10, null=True, verbose_name='Geschlecht'),
        ),
    ]
