# Generated by Django 5.0.1 on 2024-01-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ownerprofile_owner_remove_userprofile_barber_and_more'),
        ('contact', '0005_remove_galleryitem_user_galleryitem_name_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_profile', to='contact.barber', verbose_name='Friseur'),
        ),
    ]
