# Generated by Django 5.0.1 on 2024-01-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_barber'),
        ('contact', '0005_remove_galleryitem_user_galleryitem_name_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='contact.owner', verbose_name='Eigentümer'),
        ),
    ]
