# Generated by Django 5.0.1 on 2024-03-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ownerprofile_owner'),
        ('contact', '0030_owner_closing_time_owner_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='contact.owner', verbose_name='Eigentümer'),
        ),
    ]
