# Generated by Django 5.0.1 on 2024-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_ownerprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(upload_to='profile_images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Foto'),
        ),
    ]
