# Generated by Django 5.0.1 on 2024-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_salon_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='tax_id',
        ),
    ]
